### ISSUE TITLE
Gradle version too low

### ISSUE THREAD

**Issue by rickyManalo** [martinmarinov/AndroidDvbDriver#24]
Can someone update this app's gradle to at least 3.2.1? There are a lot of parts that needs to be fixed to work on Android Studio 3.0 and above.

**Comment by rickyManalo** [comment]
Sorry. Didn't

**Comment by thibautperrin** [comment]
Look at my pull request. I upgraded gradle ;-)

**Comment by rickyManalo** [comment]
Oh. Thank you. I hope they merge it already.

**Comment by rickyManalo** [comment]
Hi. I tried to apply your update on my copy and I got problems on idea/modules.xml. Once I change it's content, the files disappears on Android Studio even if I'm using the Project view. I did a Sync with File System but nothing happens. If I revert the modules.xml back to it's previous contents and do a Sync with File System, the files appear again.

**Comment by thibautperrin** [comment]
On my side, I just tried cloning from scratch, it was without any issue. Since I was on that, I upgraded for the latest gradle coming with Android Studio 3.3: 
https://github.com/thibautperrin/AndroidDvbDriver/commits/gradle-upgrade
You only have to open Android Studio, File, Open from version control, and submit the URL, and it works without asking question.

My branch is here : https://github.com/thibautperrin/AndroidDvbDriver/commits/gradle-upgrade
