### ISSUE TITLE
Any reason the driver and Aerial TV are not available in all countries?

### ISSUE THREAD

**Issue by sivantoledo** [martinmarinov/AndroidDvbDriver#3]
Hi, I tried to install both the DVBT driver and Aerial TV from Google Play, and it told me about both that they are not available in my country (Israel). I'll be happy to give them a try if they will be made available. There  are DVB-T transmissions here (in case you limit to countries with DVB-T broadcasting).

Thanks, Sivan Toledo

**Comment by martinmarinov** [comment]
Hi Sivan,

Aerial TV and its driver are restricted to countries that have DVB-T or DVB-T2 transmissions. This is so that people are not confused.

As for Israel, AerialTV and the driver are both available in Israel. It is possible that your Android thinks it's in a different country for some reason. I would encourage you to get in touch with Google if you can and ask them why your account doesn't have access to an app available in Israel.

Regards,
Martin

**Comment by martinmarinov** [comment]
![screenshot_20170502-205201](https://cloud.githubusercontent.com/assets/1353844/25636584/be727072-2f79-11e7-8841-84f1310e1857.png)

Here is a screenshot proving that Aerial TV is enabled for Israel

**Comment by sivantoledo** [comment]
Thanks a lot, I'll check.
